<link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.3.6/css/buttons.dataTables.min.css">
<link rel="stylesheet" href="{{asset('css/config/config.css')}}">
<link rel="stylesheet" href="{{asset('css/config/themes.css')}}">
<link rel="stylesheet" href="{{asset('css/config/forms.css')}}">
<link rel="stylesheet" href="{{asset('css/config/modals.css')}}">
<link rel="stylesheet" href="{{asset('css/config/loading.css')}}">
<link rel="stylesheet" href="{{asset('css/main.css')}}">
<link rel="stylesheet" href="{{asset('css/admin/products_services.css')}}">
<link rel="stylesheet" href="{{asset('css/admin/dashboard.css')}}">
<link rel="stylesheet" href="{{asset('css/admin/technicals.css')}}">
<link rel="stylesheet" href="{{asset('css/admin/repairs.css')}}">
<link rel="stylesheet" href="{{asset('css/admin/settings.css')}}">